### ISSUE TITLE
[proxy] Error while using proxy after forking pgoapi

### ISSUE THREAD

**Issue by Nik0lashka** [PokemonGoMap/PokemonGo-Map#754]
## Expected Behavior

Log in and get data through proxy
## Current Behavior

Gets error

## Log

2016-08-16 19:32:17,388 [ MainThread][ runserver][ INFO] Parsed location is: xxx/yyy/8.8079 (lat/lng/alt) 
2016-08-16 19:32:17,389 [ MainThread][ runserver][ INFO] Parsing of Pokestops disabled 
2016-08-16 19:32:17,389 [ MainThread][ runserver][ INFO] Parsing of Gyms disabled 
2016-08-16 19:32:17,397 [ MainThread][ models][ INFO] Connecting to local SQLite database 
2016-08-16 19:32:17,402 [ search_thread][ search][ INFO] Search overseer starting 
2016-08-16 19:32:17,403 [ search_thread][ search][ INFO] Starting search worker threads 
2016-08-16 19:32:17,405 [ search_thread][ search][ INFO] New location caught, moving search grid 
2016-08-16 19:32:17,407 [ search_worker_0][ search][ INFO] Search step 1 beginning (queue size is 5) 
2016-08-16 19:32:17,407 [ search_worker_0][ search][ ERROR] Exception in search_worker: AuthGoogle instance has no attribute '_session'. Username: xxx 
Traceback (most recent call last): 
File "/Users/xxx/Documents/PokemonGo-Map/pogom/search.py", line 331, in search_worker_thread check_login(args, account, api, step_location) 
File "/Users/xxx/Documents/PokemonGo-Map/pogom/search.py", line 440, in check_login api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'], proxy_config={'http': args.proxy, 'https': args.proxy}) 
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 87, in set_authentication self._auth_provider.set_proxy(proxy_config) 
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pgoapi/auth_google.py", line 50, in set_proxy self._session.proxies = proxy_config 
AttributeError: AuthGoogle instance has no attribute '_session'

## Config
auth-service:google 
username:xxx 
password:xxx 
location: xxx, yyy 
no-gyms:true # disables gym scanning (default false) 
no-pokestops:true # disables pokestop scanning (default false) 
step-limit:4 # default 12 
maps-key:xxx 
proxy: socks5://50.62.44.57:60088
## Your Environment

* Version used:290278ad500daa5b38e5ad6cec38c8bd029b4d21 (clean install)
* Environment name and version (e.g. Python 2.7):python 2.7
* Operating System and version (desktop or mobile):OS X 10.11.6

**Comment by brandonshults** [comment]
Try upgrading your dependencies: pip install -r requirements.txt --upgrade

**Comment by tboyce1** [comment]
I'm pretty sure this is an actual issue in the pgoapi that got introduced with https://github.com/PokemonGoMap/pgoapi/commit/8c6711adc7b95608ff31d0fe4a9e3090e0c8b8cc. The last line says it all: `AttributeError: AuthGoogle instance has no attribute '_session'`. The Google auth class doesn't define `self._session` before trying to assign the proxy to `self._session.proxies`.

I threw together a fix for this: https://github.com/PokemonGoMap/pgoapi/pull/1, but I don't really know what `requests.session()` does so I'm not sure if it's the correct way to fix it.

**Comment by Nik0lashka** [comment]
@brandonshults i made clean setup especially to test new proxy feature, so there is no need to upgrade dependencies - they are as new as possible. BTW if i comment out proxy string from settings, it works fine.

@tboyce1 may be @invisiblek could help, cause he added proxy features.

**Comment by pyr0ball** [comment]
Does this same behavior occur when using an external proxy source like proxychains?

**Comment by Nik0lashka** [comment]
@pyr0ball that address in my config is some free proxy server i found in google. According to https://github.com/PokemonGoMap/pgoapi/pull/1#issuecomment-240707881 we were to wait for https://github.com/simon-weber/gpsoauth/pull/16 being pulled. I will update this thread in few hours, when i return home and check it.

**Comment by pyr0ball** [comment]
@Nik0lashka let me know if you are able to reproduce again. I have a paid proxy you can use for testing if it happens again on the free one. Could possibly be an issue with the proxy server itself

**Comment by Nik0lashka** [comment]
@pyr0ball after checking tons of free socks5 proxies i found one that worked for an hour and then turned down)) You are right, issue is with proxy server.
